### ISSUE TITLE
Issue with the VenksSurvival plugin being unable to unload from server due to colorcode

### ISSUE THREAD

**Issue by TheMegaPVP** [derekdinan/ClassiCube-Stuff#2]
`namespace MCGalaxy {
    public class PvP: Plugin_Simple {
        public override string name {
            get {
                return "**&a**Venk's Survival**%S**";
            }
        }`

The &a color code prevents it from being unloaded due to cc not being able to identify the color code when using /plugin unload

**Comment by derekdinan** [comment]
As of February 2018, you can just use partial plugin names. E.g, `/punload Venk` or `/punload Surv` will both work.
