### ISSUE TITLE
Discord Verify out of date

### ISSUE THREAD

**Issue by xXNinjaKingXx** [derekdinan/ClassiCube-Stuff#20]
I tried to compile Discord verify but its giving out multiple errors i would fix it myself but i don't have the time atm please fix. @derekdinan

**Comment by derekdinan** [comment]
I just tested on both 1.9.3.1 and the latest version of MCGalaxy and it seemed to have compiled correctly. Could you please share the errors you get when compiling?

**Comment by ProgramPL** [comment]
> I tried to compile Discord verify but its giving out multiple errors i would fix it myself but i don't have the time atm please fix. 

Make sure that you have updated MCGalaxy. I compiled the latest release with 0 issues.

**Comment by derekdinan** [comment]
Going to close this as there hasn't been any response back in a while. Please feel free to reopen it after you try updating MCGalaxy if the issue persists.

**Comment by xXNinjaKingXx** [comment]
Sorry about that it logged me out and took me a while to get back in ill sen screenshots of the errors and send them to you via discord.
